### ISSUE TITLE
Option to disable automatic reindexing if configured new/addtional plugin

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#105]
Admins should be able to disable automatic reindexing/reprocessing files on file system directories recrawl if new/additional configured plugin.

**Comment by Mandalka** [comment]
Implemented new config option do_not_reindex_because_plugin_yet_not_processed (array of plugin names)

Example setting for not automatically reindex yet indexed files because of setup (new default settings) of new plugins for email address and phone number extraction:

config['do_not_reindex_because_plugin_yet_not_processed'] = ['enhance_extract_email', 'enhance_extract_phone']
