### ISSUE TITLE
Disable OCR / tesseract

### ISSUE THREAD

**Issue by nevermind2001** [opensemanticsearch/open-semantic-etl#125]
Hey,

i installed opensemanticsearch in an ubuntu container. i added a mounted network folder with all my pdfs. they are already ocred. i think i disabled ocr in open semantic search but as soon as i start the vm i have up to 4 tesseract jobs running an the vm has 100% cpu usage. what is this and how can i avoid it?

Maybe i have to disable ocr in tika? i googled a lot but i dont understand how to it. Would be great if someone can help me.

thanks a lot

![top](https://user-images.githubusercontent.com/44928988/78452715-274c4e80-768d-11ea-891f-b8da8d5c10af.JPG)

**Comment by Mandalka** [comment]
If you installed the full search engine all in one package:

Click on "Config", select tab "OCR" and just disable "OCR" and disable "OCR images in PDF".

Since you wrote in the repository of ETL package:

If you use only the ETL package, you can disable ocr and the plugin enhance_pdf_ocr in /etc/opensemanticsearch/etl (dont do that if the full search engine installed, since will be overwritten by the config UI)
