### ISSUE TITLE
missing etl_tasks.py

### ISSUE THREAD

**Issue by dhyams** [opensemanticsearch/open-semantic-etl#17]
There is a symlink from /usr/bin/etl_tasks.py -> /usr/lib/python3/dist-packages/opensemanticetl/etl_tasks.py

However,  /usr/lib/python3/dist-packages/opensemanticetl/etl_tasks.py does not exist; rather a file named tasks.py exists in that directly.

If you create a symlink from /usr/lib/python3/dist-packages/opensemanticetl/tasks.py to /usr/lib/python3/dist-packages/opensemanticetl/etl_tasks.py, that gets the file monitoring working again.

I doubt if this is the way that you want to fix this problem, but I thought it important to point out.

**Comment by dhyams** [comment]
This may not be the only problem; I am having a rough time getting OpenSemanticSearch to index files properly on a fresh Debian Stretch install using the opensemanticsearch-server package.  Adding a bunch of files to a monitored directly doesn't seem to work well; it will pick up one of the files, but only one.  And when I remove files from a watched directory, it doesn't remove them from the index.

I am using open-semantic-search_17_08.21.deb.

Is there a forum for opensemanticsearch for discussion of problems/solutions?

**Comment by Mandalka** [comment]
Thanks for bug report.

Old Debian symlinks now [changed](https://github.com/opensemanticsearch/open-semantic-etl/commit/8f691ca48e783c704eac83d5cd7df61e33e57b12) to new filenames.

**Comment by Mandalka** [comment]
File monitoring needs to initialize after boot / restart and the old version has problems because of Python 2 encoding problems if special chars in filenames and not UTF-8 charset set in Debian.

Is it a directory with thousands/hundretthousands of files/subdirectories? In such cases it takes minutes until file monitoring is active for all files and subdirectories. Therefore sometimes its important to reindex with the crawler from time to time for the case that a file is changed while initialization.

Please try the release which will be available for download next week and reopen if problem exists with python 3 based API and file monitoring script.

**Comment by dhyams** [comment]
Thanks for the fix.  I will look for the new version next week.

I was only adding 1-6 files into the monitored directory, to see what the results were.  I started from an empty index, so the only files in the index were the ones that might make it in via the file monitoring.  I could tell that the pyinotify part was working, because I placed print statements inside the etl_*.py scripts.
