### ISSUE TITLE
Files added to index by file monitoring don't obey mapping

### ISSUE THREAD

**Issue by dhyams** [opensemanticsearch/open-semantic-etl#18]
[using the 8/26 version of opensemanticsearch]

Attempting to add files to index with the file monitor; they seem to be added into the index, but they ignore the "mappings" setting in /etc/opensemanticsearch/connector-files.  Because of this, any files that show up in the search cannot be clicked-on and download in the interface.

Files added manually with opensemanticsearch-index-file work fine.

There's a comment in /usr/bin/opensemanticsearch-filemonitoring that says "TODO: read from config file" that is likely related.

**Comment by opensemanticsearch** [comment]
Has nothing to do with read mapping from config file todo, this should be necessary only for delete because uris are yet mapped filenames, which is done now. The mapping for indexing is done by a plugin.

But it can be reproduced and fixed.

**Comment by opensemanticsearch** [comment]
Has nothing to do with read mapping from config file todo, this should be necessary only for delete because URIs are yet mapped filenames, which is done now. The mapping for indexing is done by a plugin.

A test here worked after restarted opensemanticsearch ETL workers / reboot which is started automatically on boot and will read this mapping config while service start.

If you use the command line tools the config changes will be considered on next run, thats why it worked after change without restart of the service.

If mapping config should not work after a reboot or restart of Open Semantic ETL daemon please reopen.
