### ISSUE TITLE
Knowledge graph: Mapping RDF class to facet

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#38]
Add mapping for rdf:type to facet and write RDF label or SKOS label of RDF entities to that facet, so Entities from Knowledge Graph that do not occur in documents are shown in new UI view "Named Entities", too, which is based on facets.

**Comment by Mandalka** [comment]
Since human readable labels of RDF entities with RDF classes now additionally added to (mapped) facets of the class, the entities of knowledge graph are included in the view "Named entities" and the knowledge graph entities themselves can be listed / filtered together with entities of named entity recognition by facets like persons, organizations or locations (like it is/was possible for properties/facets for linked other entities).
