### ISSUE TITLE
Why not use dataimporthandlers from solr?

### ISSUE THREAD

**Issue by agcunha** [opensemanticsearch/open-semantic-etl#68]
why OSS doesn't use the solr dataimporthandlers? Python scripts gives more flexibility?

**Comment by Mandalka** [comment]
Yes, much more flexibility/frameworks/libs/integrations, since for example (please correct me if wrong) i don't see an easy possibility how to add IF statements to do different data processing chains of other Solr fields based on other fields/values like language or only if some special data/values if not using the javascripting interface of Solr (i am more familar with Python, so i use it on ETL level (which can so run separeted) instead of javascript on Solr level).
