### ISSUE TITLE
Consider upgrading to tika-python 

### ISSUE THREAD

**Issue by chrismattmann** [opensemanticsearch/open-semantic-etl#7]
There is a tika-python library here https://github.com/chrismattmann/tika-python that could replace the system calls to tika java. I can submit a PR if there is interest?

**Comment by Mandalka** [comment]
Thank you for info.

The plugins with command line calls of Tika (enhance_extract_text.py and enhance_extract_metadata.py) are not active in default setup.

The used default ETL plugin for Tika https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/etl/enhance_extract_text_tika_server.py using a Tika server for performance issues (no reload & new initialization of Tika.jar for every file/document).

Would usage of your module be more performant or providing other advantages than the way in this plugin (where i would improve/abstract some mapping calls to more readable dictionary configs)?

I'll consider that for next features like language detection needed for planned multilingual search/stemming, instead reinvent the wheel.

Since Tika can be used to unpack archives, is this implemented in tika-python ?

What i like very much is if Python packages are in Debian, so a apt-get install python-... or only defining a dependency in the search engine packages are enough to install it.

**Comment by chrismattmann** [comment]
Tika-python transparently calls the rest server and is on lock step with Tika releases. Also works with all tika interfaces and yes supports unpack.

**Comment by chrismattmann** [comment]
ping @Mandalka just checking if you saw my above referenced comment? Thanks.

**Comment by Mandalka** [comment]
Migrated the Tika Server extraction plugin from pycurl to python-tika.

**Comment by Mandalka** [comment]
The needed tika-python library is served for the Open Semantic Search packages and VMs by the Debian package https://github.com/opensemanticsearch/tika-python.deb
