### ISSUE TITLE
neo4j plugin not working

### ISSUE THREAD

**Issue by bhelou** [opensemanticsearch/open-semantic-etl#70]
Hi,

For the export_neo4j plugin, I get the following exception

```
Exception while data enrichment of has_images.pdf with plugin export_neo4j: Primary label and primary key are required for MERGE operation
```

It happens on all files and just in case it doesn't, I've attached a file where the exception occurred for sure: [test.txt](https://github.com/opensemanticsearch/open-semantic-etl/files/2150483/test.txt).

To fix it, I use transactions. Specifically, I changed  

```python
graph.merge(document_node)
```
to 
```python
tx = graph.begin()
tx.merge(document_node, primary_label = "Document", primary_key = "name")
```
and
```python
graph.merge(entity_node)
```
to 
```python
tx.merge(entity_node, primary_label = entity_class_label, primary_key = 'name')
```
and 
```python
graph.merge(relationship)
```
to 
```python
tx.merge(relationship, primary_label = relationship_label)
```
At the end of the process function, I've added
```python
tx.commit()
```

neo4j now works. I don't know though if there's a better way to do the above (I just learned about neo4j :p).

Also, when I try to reset my OSS index (via `opensemanticsearch-delete --empty`), it doesn't empty the neo4j database. To remove it, I delete the database files via `rm -rf /opt/neo4j/data/databases/*`. I then restart neo4j via `service neo4j restart`.
I'm not sure if this is a bug or a feature, but I thought I'd mention it.

Thanks for the OSS software!
Bassam

**Comment by ptmaroct** [comment]
Hi, after making these changes, I did get some progress however I got stuck again due to following error. The command I ran was:

$ etl-web http://anujsh.com

![selection_157](https://user-images.githubusercontent.com/13233320/50624900-40c29000-0f4a-11e9-83c8-2bb217a0dc5d.png)

**Comment by Mandalka** [comment]
I upgraded to newest Neo4j and the new py2neo 4 seems to work with the py2neo lib instead of underlaying Neo4j Driver for Python, so i changed the pip3 install to use py2neo 4 again.

Maybe for upgrading you need to
pip3 uninstall py2neo
first if yet pinned to version 3.x

Maybe the DB format changed, so Neo4j db has to be deleted like described below.

Please reopen (or i will if further tests on fresh debian will cause problems) if yet problems after upgrade to Neo4j 3.5.2 and Py2neo 4.x and newest Open Semantic ETL.
