### ISSUE TITLE
no data export to Neo4J

### ISSUE THREAD

**Issue by ronaldoviber** [opensemanticsearch/open-semantic-etl#76]
on a fresh debian stretch: there is no export of entities to neo4j.

Version: open-semantic-search_18.12.23

already installed: py2neo + export_neo4j, and activated by config!

no logs, something missing?

**Comment by ptmaroct** [comment]
Had the same issue. I think it is due to some broken code in export_neo4j.py plugin which is responsible for sending data to neo4j.
There was a minor fix that I found, which was to manually update the code in python file so that it used commit for transaction in neo4j and I was partially successful in populating neo4j database.
Check: [issue #70 ](https://github.com/opensemanticsearch/open-semantic-etl/issues/70)

**Comment by Mandalka** [comment]
Maybe there were changes in py2neo which evolved last year, if using newer releases than when i implemented the plugin.

I'll check / merge / test / upgrade to newest Neo4j and py2neo releases while migrating the plugin to new named entity API strucutures (which then in neo4j too will use the SKOS IDs for then possible disambiguation instead of only labels) in january.

**Comment by ptmaroct** [comment]
Amazing! Looking forward to new release and thank you for the software! Are you free for some 10 minutes? I would like to talk to you @Mandalka

**Comment by Mandalka** [comment]
@ptmaroct i'll have some free time next week, since yet some stuff to document/release this week.

**Comment by opensemanticsearch** [comment]
Merged https://github.com/opensemanticsearch/open-semantic-etl/pull/77 until upgrade to newest Neo4j and Py2Neo.

**Comment by Mandalka** [comment]
Since doesn't work on fresh Debian pinned again to py2neo 3.x until upgrade when migrate to new ID/URI instead string based entities in Neo4j.
